# Generated by Django 2.1.7 on 2019-04-11 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('income', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('driver_lat', models.FloatField(default=None, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
                ('driver_long', models.FloatField(default=None, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.SmallIntegerField(default=-1)),
                ('driver_id', models.SmallIntegerField(default=-1)),
                ('customer_lat', models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-1)])),
                ('customer_long', models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-1)])),
                ('order_price', models.FloatField(default=0)),
                ('fee', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('S1', 'Looking drivers'), ('S2', 'Waiting pick up'), ('S3', 'Sending an order'), ('S4', 'delivered')], default='S1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('time_joined', models.DateField(auto_now_add=True)),
                ('restaurant_name', models.CharField(max_length=50)),
                ('income', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rest_lat', models.FloatField(default=None, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
                ('rest_long', models.FloatField(default=None, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField(max_length=16)),
            ],
        ),
    ]
