# Generated by Django 2.1.7 on 2019-03-18 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('time_joined', models.DateField(auto_now_add=True)),
                ('ssn', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(100000000)])),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('income', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('car_plate', models.CharField(max_length=10)),
                ('car_model', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('time_joined', models.DateField(auto_now_add=True)),
                ('restaurant_name', models.CharField(max_length=50)),
                ('income', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
