# Generated by Django 2.1.7 on 2019-03-25 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.SmallIntegerField(default=-1)),
                ('driver_id', models.SmallIntegerField(default=-1)),
                ('customer_lat', models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-1)])),
                ('customer_long', models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-1)])),
                ('order_price', models.SmallIntegerField(default=0)),
                ('fee', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='location',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_lat',
            field=models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_long',
            field=models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_lat',
            field=models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_long',
            field=models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
