# Generated by Django 2.0.13 on 2019-04-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='token',
            name='user_id',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
