# Generated by Django 2.1.7 on 2019-03-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
