# Generated by Django 2.1.7 on 2019-03-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_driver_occupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='car_plate',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='time_joined',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
    ]
