# Generated by Django 2.1.7 on 2019-03-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190325_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0),
        ),
    ]
