# Generated by Django 2.1.7 on 2019-03-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_name', models.CharField(max_length=200)),
                ('costumer_phone', models.CharField(max_length=100)),
                ('costumer_address', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=300)),
                ('order_placed_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
